import React from "react"
import { AbsoluteFill, Composition, interpolate, registerRoot, useCurrentFrame } from "remotion"

type Manifest = {
  title: string
  script: string
  captions: string[]
  metadata?: {
    hashtags?: string[]
  }
}

const defaultManifest: Manifest = {
  title: "ReelOps",
  script: "Automated reel generated by ReelOps.",
  captions: ["Automated reel generated by ReelOps."],
  metadata: { hashtags: ["#reels", "#ai"] }
}

function Reel({ manifest = defaultManifest }: { manifest?: Manifest }) {
  const frame = useCurrentFrame()
  const captions = manifest.captions?.length ? manifest.captions : [manifest.script]
  const activeIndex = Math.min(captions.length - 1, Math.floor(frame / 110))
  const progress = interpolate(frame, [0, 900], [0, 100], { extrapolateRight: "clamp" })
  const scale = interpolate(frame % 110, [0, 30, 110], [0.98, 1.02, 1], { extrapolateRight: "clamp" })

  return (
    <AbsoluteFill style={{ backgroundColor: "#101714", color: "white", fontFamily: "Inter, Arial, sans-serif" }}>
      <AbsoluteFill
        style={{
          background:
            "radial-gradient(circle at 20% 15%, rgba(36, 130, 104, 0.55), transparent 34%), radial-gradient(circle at 85% 80%, rgba(177, 116, 33, 0.5), transparent 30%), linear-gradient(160deg, #101714, #1d2a25 52%, #111513)"
        }}
      />
      <div style={{ position: "absolute", top: 76, left: 70, right: 70 }}>
        <div style={{ color: "#f0bd67", fontSize: 28, fontWeight: 800, letterSpacing: 0 }}>REELOPS</div>
        <h1 style={{ margin: "18px 0 0", fontSize: 74, lineHeight: 1.02, letterSpacing: 0 }}>{manifest.title}</h1>
      </div>
      <div
        style={{
          position: "absolute",
          left: 70,
          right: 70,
          top: 610,
          minHeight: 620,
          display: "grid",
          placeItems: "center",
          transform: `scale(${scale})`
        }}
      >
        <div
          style={{
            fontSize: 66,
            lineHeight: 1.12,
            fontWeight: 850,
            textAlign: "center",
            textShadow: "0 10px 40px rgba(0,0,0,0.5)"
          }}
        >
          {captions[activeIndex]}
        </div>
      </div>
      <div style={{ position: "absolute", left: 70, right: 70, bottom: 170 }}>
        <div style={{ height: 10, borderRadius: 999, background: "rgba(255,255,255,0.18)", overflow: "hidden" }}>
          <div style={{ width: `${progress}%`, height: "100%", background: "#f0bd67" }} />
        </div>
        <div style={{ marginTop: 30, fontSize: 30, color: "rgba(255,255,255,0.8)" }}>
          {(manifest.metadata?.hashtags || ["#reels", "#shorts"]).join(" ")}
        </div>
      </div>
    </AbsoluteFill>
  )
}

function Root() {
  return (
    <Composition
      id="ReelOpsReel"
      component={Reel}
      durationInFrames={900}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ manifest: defaultManifest }}
    />
  )
}

registerRoot(Root)

