from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from ..config import settings
from ..models import ReelJob


def _srt_time(seconds: int) -> str:
    return f"00:00:{seconds:02d},000"


def write_caption_files(job_dir: Path, lines: list[str]) -> dict[str, str]:
    srt_lines: list[str] = []
    vtt_lines = ["WEBVTT", ""]
    for index, text in enumerate(lines, start=1):
        start = (index - 1) * 4
        end = start + 4
        srt_lines.extend([str(index), f"{_srt_time(start)} --> {_srt_time(end)}", text, ""])
        vtt_lines.extend([f"00:00:{start:02d}.000 --> 00:00:{end:02d}.000", text, ""])
    srt = job_dir / "captions.srt"
    vtt = job_dir / "captions.vtt"
    srt.write_text("\n".join(srt_lines), encoding="utf-8")
    vtt.write_text("\n".join(vtt_lines), encoding="utf-8")
    return {"srt": str(srt), "vtt": str(vtt)}


def render_job(job: ReelJob) -> dict[str, Any]:
    job_dir = settings.artifacts_dir / "jobs" / job.id
    capcut_dir = job_dir / "capcut"
    job_dir.mkdir(parents=True, exist_ok=True)
    capcut_dir.mkdir(parents=True, exist_ok=True)

    script = job.payload.get("script", {}).get("script") or f"{job.title}. Generated by ReelOps."
    prompt_lines = job.payload.get("prompts", {}).get("video_prompts") or [script]
    metadata = {
        "title": job.title,
        "platform": job.platform,
        "language": job.language,
        "description": f"Generated ReelOps export for {job.title}.",
        "hashtags": ["#reels", "#ai", "#shorts"],
    }
    manifest = {
        "job_id": job.id,
        "title": job.title,
        "script": script,
        "captions": prompt_lines[:8],
        "metadata": metadata,
        "assets": job.artifacts.get("assets", []),
    }

    manifest_path = job_dir / "manifest.json"
    prompts_path = job_dir / "prompts.json"
    metadata_path = job_dir / "metadata.json"
    script_path = job_dir / "script.txt"
    thumbnail_path = job_dir / "thumbnail.txt"
    timeline_json_path = capcut_dir / "timeline.json"
    timeline_csv_path = capcut_dir / "timeline.csv"
    out_video = job_dir / "reel.mp4"

    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    prompts_path.write_text(json.dumps(job.payload.get("prompts", {}), indent=2), encoding="utf-8")
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    script_path.write_text(script, encoding="utf-8")
    thumbnail_path.write_text(f"Thumbnail placeholder for {job.title}\n", encoding="utf-8")
    timeline_json_path.write_text(json.dumps({"clips": prompt_lines, "voiceover": "script.txt"}, indent=2), encoding="utf-8")
    timeline_csv_path.write_text("index,type,label,duration\n1,voiceover,script,auto\n", encoding="utf-8")
    caption_files = write_caption_files(job_dir, [str(x) for x in prompt_lines[:8]])

    render_result: dict[str, Any] = {"mode": settings.render_mode, "ok": False}
    if settings.render_mode == "remotion":
        repo_root = Path(__file__).resolve().parents[3]
        try:
            completed = subprocess.run(
                [
                    "npm",
                    "run",
                    "render",
                    "--workspace",
                    "renderer",
                    "--",
                    "--manifest",
                    str(manifest_path),
                    "--out",
                    str(out_video),
                ],
                cwd=repo_root,
                check=False,
                capture_output=True,
                text=True,
                timeout=600,
            )
            render_result.update(
                {
                    "ok": completed.returncode == 0,
                    "stdout": completed.stdout[-2000:],
                    "stderr": completed.stderr[-2000:],
                    "returncode": completed.returncode,
                }
            )
        except Exception as exc:
            render_result.update({"error": str(exc)})

    if not out_video.exists():
        out_video.write_bytes(b"ReelOps placeholder MP4. Install renderer dependencies to render real video.\n")

    return {
        "job_dir": str(job_dir),
        "video": str(out_video),
        "manifest": str(manifest_path),
        "script": str(script_path),
        "prompts": str(prompts_path),
        "metadata": str(metadata_path),
        "thumbnail": str(thumbnail_path),
        "captions": caption_files,
        "capcut": {"dir": str(capcut_dir), "timeline_json": str(timeline_json_path), "timeline_csv": str(timeline_csv_path)},
        "render_result": render_result,
    }

